### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by bkamphues** [nfa-vfxim/tk-maya-usd#1]
# To-Do
- [ ] Update documentation on [wiki.vfxim.nl](https://wiki.vfxim.nl/).
- [ ] Create a wiki section on this repository for installation and configuration instructions.
- [ ] Update `documentation_url` in `info.yml`.
